url: local
workingDir: charts
packageVersion: 03
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
# whereabouts is only used as a dependency of multus
doNotRelease: true
